// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: magicdbapi.proto

package mapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Magicdb_Get_FullMethodName = "/api.magicdb/Get"
)

// MagicdbClient is the client API for Magicdb service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MagicdbClient interface {
	Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type magicdbClient struct {
	cc grpc.ClientConnInterface
}

func NewMagicdbClient(cc grpc.ClientConnInterface) MagicdbClient {
	return &magicdbClient{cc}
}

func (c *magicdbClient) Get(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Response)
	err := c.cc.Invoke(ctx, Magicdb_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MagicdbServer is the server API for Magicdb service.
// All implementations must embed UnimplementedMagicdbServer
// for forward compatibility.
type MagicdbServer interface {
	Get(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedMagicdbServer()
}

// UnimplementedMagicdbServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMagicdbServer struct{}

func (UnimplementedMagicdbServer) Get(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMagicdbServer) mustEmbedUnimplementedMagicdbServer() {}
func (UnimplementedMagicdbServer) testEmbeddedByValue()                 {}

// UnsafeMagicdbServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MagicdbServer will
// result in compilation errors.
type UnsafeMagicdbServer interface {
	mustEmbedUnimplementedMagicdbServer()
}

func RegisterMagicdbServer(s grpc.ServiceRegistrar, srv MagicdbServer) {
	// If the following call pancis, it indicates UnimplementedMagicdbServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Magicdb_ServiceDesc, srv)
}

func _Magicdb_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagicdbServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Magicdb_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagicdbServer).Get(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Magicdb_ServiceDesc is the grpc.ServiceDesc for Magicdb service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Magicdb_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.magicdb",
	HandlerType: (*MagicdbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Magicdb_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "magicdbapi.proto",
}
