cache_size = 100000
work_dir = "/tmp/magicdb"
[server]
project_name = "magicdb_engine"
grpc_port = 6527
http_port = 6528
prome_port = 6529
pprof_port = 6530
debug = true
[server.register.etcd]
endpoints=["127.0.0.1:2379"]
name="magicdb"